name: Pull request checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Clear cache
        run: chown -R 1001:1001 /github/home/.cache && echo "pwn dat cache"
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
#          cache: 'npm'
      - run: npm install
      - run: npm run code-style
 #     - run: npm run test